<template>
  <patient-header></patient-header>
  <breadcrumb1 :title="title" :text="text" :text1="text1" />
  <div class="content doctor-content">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-xl-3 theiaStickySidebar">
          <!-- Profile Sidebar -->
          <profilesidebar></profilesidebar>
          <!-- /Profile Sidebar -->
        </div>

        <!-- Change Password -->
        <div class="col-lg-8 col-xl-9">
          <nav class="settings-tab mb-1">
            <ul class="nav nav-tabs-bottom" role="tablist">
              <li class="nav-item" role="presentation">
                <router-link class="nav-link" to="/profile-settings">Profile</router-link>
              </li>
              <li class="nav-item" role="presentation">
                <router-link class="nav-link" to="/change-password"
                  >Change Password</router-link
                >
              </li>
              <li class="nav-item" role="presentation">
                <router-link class="nav-link active" to="/two-factor-authentication"
                  >2 Factor Authentication</router-link
                >
              </li>
              <li class="nav-item" role="presentation">
                <router-link class="nav-link" to="/delete-account"
                  >Delete Account</router-link
                >
              </li>
            </ul>
          </nav>
          <div class="card mb-0">
            <div class="card-body">
              <div
                class="border-bottom d-flex align-items-center justify-content-between gap-3 flex-wrap pb-3 mb-3"
              >
                <h5>2 Factor Authentication</h5>
                <div class="status-toggle">
                  <input type="checkbox" id="status_2" class="check" checked />
                  <label for="status_2" class="checktoggle">checkbox</label>
                </div>
              </div>
              <div class="card">
                <div class="card-body">
                  <form action="#">
                    <div class="mb-3">
                      <h6 class="mb-1">Set up using an Email</h6>
                      <p class="fs-14">Enter your Email which we send you code</p>
                    </div>
                    <div class="mb-3 pb-3 border-bottom">
                      <label class="form-label"
                        >Email Address <span class="text-danger">*</span></label
                      >
                      <div class="d-flex align-items-center w-100 gap-2">
                        <div class="flex-grow-1">
                          <input type="text" class="form-control" />
                        </div>
                        <div>
                          <button class="btn btn-md btn-primary-gradient rounded-pill">
                            Continue
                          </button>
                        </div>
                      </div>
                    </div>
                    <label class="form-label">Enter the code generated by Email</label>
                    <div
                      method="get"
                      class="digit-group login-form-control"
                      data-group-name="digits"
                      data-autosubmit="false"
                      autocomplete="off"
                    >
                      <div class="otp-box setting-otp">
                        <div class="mb-2">
                          <input
                            type="text"
                            id="digit-1"
                            name="digit-1"
                            data-next="digit-2"
                            maxlength="1"
                          />
                          <input
                            type="text"
                            id="digit-2"
                            name="digit-2"
                            data-next="digit-3"
                            data-previous="digit-1"
                            maxlength="1"
                          />
                          <input
                            type="text"
                            id="digit-3"
                            name="digit-3"
                            data-next="digit-4"
                            data-previous="digit-2"
                            maxlength="1"
                          />
                          <input
                            type="text"
                            id="digit-4"
                            name="digit-4"
                            data-next="digit-5"
                            data-previous="digit-3"
                            maxlength="1"
                          />
                        </div>
                      </div>
                    </div>
                    <button
                      type="submit"
                      class="btn btn-md btn-primary-gradient rounded-pill"
                    >
                      Submit
                    </button>
                  </form>
                </div>
              </div>
              <div class="card mb-0">
                <div class="card-body">
                  <form action="two-factor-authentication.html">
                    <div class="mb-3">
                      <h6 class="mb-1">Set up using an SMS</h6>
                      <p class="fs-14">Enter your phone number which we send you code</p>
                    </div>
                    <div class="mb-3 pb-3 border-bottom">
                      <label class="form-label"
                        >Phone Number <span class="text-danger">*</span></label
                      >
                      <div class="d-flex align-items-center w-100 gap-2">
                        <div class="flex-grow-1">
                          <input type="text" class="form-control" />
                        </div>
                        <div>
                          <a
                            href="#"
                            class="btn btn-md btn-primary-gradient rounded-pill"
                            data-bs-target="#success-modal"
                            data-bs-toggle="modal"
                            >Continue</a
                          >
                        </div>
                      </div>
                    </div>
                    <label class="form-label">Enter the code generated by SMS</label>
                    <div
                      method="get"
                      class="digit-group login-form-control"
                      data-group-name="digits"
                      data-autosubmit="false"
                      autocomplete="off"
                    >
                      <div class="otp-box setting-otp">
                        <div class="mb-2">
                          <input
                            type="text"
                            id="digit-1"
                            name="digit-1"
                            data-next="digit-2"
                            maxlength="1"
                          />
                          <input
                            type="text"
                            id="digit-2"
                            name="digit-2"
                            data-next="digit-3"
                            data-previous="digit-1"
                            maxlength="1"
                          />
                          <input
                            type="text"
                            id="digit-3"
                            name="digit-3"
                            data-next="digit-4"
                            data-previous="digit-2"
                            maxlength="1"
                          />
                          <input
                            type="text"
                            id="digit-4"
                            name="digit-4"
                            data-next="digit-5"
                            data-previous="digit-3"
                            maxlength="1"
                          />
                        </div>
                      </div>
                    </div>
                    <button
                      type="submit"
                      class="btn btn-md btn-primary-gradient rounded-pill"
                    >
                      Submit
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Change Password -->
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      title: "Patient",
      text: "Settings",
      text1: "Settings",
    };
  },
};
</script>
